services:
  - type: web
    name: telegram-sms-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: SMS_ACTIVATE_API_KEY
        sync: false
      - key: ADMIN_IDS
        sync: false
      - key: WEBHOOK_URL
        sync: false
      - key: PORT
        value: 8080
