services:
  - type: web
    name: telegram-sms-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        value: your_bot_token_here
      - key: SMS_ACTIVATE_API_KEY
        value: your_sms_activate_api_key_here
      - key: ADMIN_IDS
        value: "123456789"
